POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imxva2tpMTIzIiwiaWQiOiI2NTUzM2FmZjMzZmIxOTg1OTAwMTFiMzEiLCJpYXQiOjE2OTk5NjY1ODd9.pQ2LN1J6oeYz-ZeVGrtAAUs3Sz6vx1uXPHDb_IXsFRY

{
    "title": "testi",
    "author": "mina",
    "url": "www.google.fi",
    "likes": "300",
    "userId": "654e209199a1a5a031592772"
}
